export const GET_USER_INPUT = "GET_USER_INPUT";
export const ADD_TODO = "ADD_TODO";
export const GET_TODO = "GET_TODO";
export const DELETE_ITEM = "DELETE_ITEM";

export const ADD_LOGIN_INPUT = "ADD_LOGIN_INPUT";
export const LOGGING_ERROR = "LOGGING_ERROR";
export const USER_IS_LOGGEDIN = "USER_IS_LOGGEDIN";

export const ADD_REGISTER_INPUT = "ADD_REGISTER_INPUT";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const REGISTER_SUCCESSFUL = "REGISTER_SUCCESSFUL";
export const USER_LOGOUT = "USER_LOGOUT";
